name: Publish

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: docker/setup-qemu-action@v3.0.0
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5.3.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/frontend
          tags: |
            type=schedule
            type=sha
            type=ref,event=branch
            type=raw,latest
      - name: Build and Push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
